Support downloads in multi server setup or serverless
Maatwebsite/Laravel-Nova-Excel pull request #122
Opened 2021-08-12 08:21 UTC by juliusvdijk

Fixes #119 

This implementation re-uses the Laravel Excel config.
I've chosen this approach as the situations where a user would use `excel.temporary_files.remote_disk` (multiple application servers or serverless) also require the Download action to store the file remotely.

2021-08-12 15:48 UTC, patrickbrouwers requested changes

2021-08-12 15:48 UTC, patrickbrouwers commented on src/Http/Controllers/ExcelController.php
> +                \Storage::disk(config('excel.temporary_files.remote_disk'))->delete($decryptedPath);
Can you use the FQN of Storage facade as this will break if someone decides to remove the aliases in their config.

2021-08-12 15:48 UTC, patrickbrouwers commented on src/Actions/DownloadExcel.php
> +    <?php
Whitespace in front of `<php`

2021-08-16 10:14 UTC, juliusvdijk commented on src/Actions/DownloadExcel.php
> +    <?php
Done

2021-08-16 11:36 UTC, merged